name: laserdrop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  http: ^1.2.0
  image: ^4.2.0
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2 # Added for storing metadata
  mockito: ^5.4.5
  build_runner: ^2.4.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Regular.ttf
        - asset: assets/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Poppins-Medium.ttf
          weight: 500
